// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm8LT8lXn5gO-6US9TmtuyPH2UD0dbPj4',
    appId: '1:6177666065:web:79439bb5c5b6fa96166db0',
    messagingSenderId: '6177666065',
    projectId: 'fluttertaskapp-e0ff1',
    authDomain: 'fluttertaskapp-e0ff1.firebaseapp.com',
    storageBucket: 'fluttertaskapp-e0ff1.firebasestorage.app',
    measurementId: 'G-5S7V5VPN1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL1s7to67hWzVbUPZCfRH8zIxrRH1jB7s',
    appId: '1:6177666065:android:b4c35142e9a23a3e166db0',
    messagingSenderId: '6177666065',
    projectId: 'fluttertaskapp-e0ff1',
    storageBucket: 'fluttertaskapp-e0ff1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAefP8hgwU0WjmnGt3uNbfvMjbLi0QcgaA',
    appId: '1:6177666065:ios:2dd7621a1ff27026166db0',
    messagingSenderId: '6177666065',
    projectId: 'fluttertaskapp-e0ff1',
    storageBucket: 'fluttertaskapp-e0ff1.firebasestorage.app',
    iosClientId: '6177666065-igqdpbdlk3uk3o0cpcqb3ibtfaqhhebt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTaskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAefP8hgwU0WjmnGt3uNbfvMjbLi0QcgaA',
    appId: '1:6177666065:ios:2dd7621a1ff27026166db0',
    messagingSenderId: '6177666065',
    projectId: 'fluttertaskapp-e0ff1',
    storageBucket: 'fluttertaskapp-e0ff1.firebasestorage.app',
    iosClientId: '6177666065-igqdpbdlk3uk3o0cpcqb3ibtfaqhhebt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTaskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm8LT8lXn5gO-6US9TmtuyPH2UD0dbPj4',
    appId: '1:6177666065:web:1db87ccdc28ca8ea166db0',
    messagingSenderId: '6177666065',
    projectId: 'fluttertaskapp-e0ff1',
    authDomain: 'fluttertaskapp-e0ff1.firebaseapp.com',
    storageBucket: 'fluttertaskapp-e0ff1.firebasestorage.app',
    measurementId: 'G-7GKYCQNLNT',
  );
}
